embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"white\"\n"
  "material: \"/materials/upscale.material\"\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "size {\n"
  "  x: 320.0\n"
  "  y: 240.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/upscale.atlas\"\n"
  "}\n"
  "textures {\n"
  "  sampler: \"world_sampler\"\n"
  "  texture: \"/main/upscale.atlas\"\n"
  "}\n"
}
